version: "3.9"
services:
  app:
    image: eclipse-temurin:17
    ports:
      - 8080:8080
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    tty: true

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  web:
    image: nginx
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d
      - ./web/log:/var/log/nginx
      - ./web/html:/var/www/html
      - ./web/letsencrypt:/etc/letsencrypt
    env_file:
      - ./environments/common.env
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

  certbot:
    image: certbot/certbot:v1.7.0
    volumes:
      - ./web/letsencrypt:/etc/letsencrypt
      - ./web/html:/var/www/html
    command: ["--version"]

volumes:
  db-store:
